name: Action CI

on:
  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Verify action syntax
        # The action should not publish any real changes, but should succeed.
        uses: './'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: '${{ github.ref }}'
